### ISSUE TITLE
About the motion data

### ISSUE THREAD

**Issue by b224618** [ZijieH/LG-ODE#1]
Hi! Thanks a lot for sharing the code!

When trying to run the experiments with motion data, I found that the code for loading the data is for loading .npy data which is same as the simulated data. Could you please provide the code for converting the raw data format from MOCAP into the .npy format?

Thanks in advance!

**Comment by ZijieH** [comment]
Hi,
    I obtained some necessary preprocessing codes from the authors at https://github.com/ethanfetaya/NRI. If you can obtain firstly the files from them, I am happy to provide the scripts for generating the mocap data in my experiment :)

**Comment by b224618** [comment]
> Hi, I obtained some necessary preprocessing codes from the authors at https://github.com/ethanfetaya/NRI. If you can obtain firstly the files from them, I am happy to provide the scripts for generating the mocap data in my experiment :)

Hi, yes I also downloaded the code from  https://github.com/ethanfetaya/NRI. May I know how would you share the scripts for generating the mocap data? Thanks a lot!
