### ISSUE TITLE
torchdiffeq version

### ISSUE THREAD

**Issue by joeloskarsson** [ZijieH/LG-ODE#2]
Thank you for sharing the code to your interesting paper!

When trying to set up the environment I realized that many versions have been released of torchdiffeq. After testing multiple of them I came to the conclusion that version 0.1.1 is the latest one that seems to work with pytorch version 1.4.0. This was also the latest version of torchdiffeq when the LG-ODE code was released I think. Thought this could be useful knowledge for anyone else using this code and perhaps something to add in the readme.

**Comment by ZijieH** [comment]
Hi Joel, 
     Thanks for the reminder and I have added the version for torchdiffeq in my experiment.

**Comment by joeloskarsson** [comment]
Great, thank you!
